---
  - name: Install Red Hat Security Advisory (RHSA)
    command: yum -y update-minimal --advisory {{ rhsa_to_install }}
    register: yum_output
  - debug: var=yum_output

  - name: Check if reboot is needed
    shell:
      cmd: /usr/bin/needs-restarting -r
    register: needs_restarting
    changed_when: False
    failed_when: False

  - name: Reboot Host if packages were updated
    reboot:
    when: needs_restarting.rc is defined and needs_restarting.rc != 0
